artifact_uri: file:///E:/Pet%20Projects/Kaggle%20Playground/binary_classification_bank/models/mlflow_artifacts/0/b71638bc8cb8458984fbb95e761ef3e0/artifacts
end_time: 1762955977426
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b71638bc8cb8458984fbb95e761ef3e0
run_name: masked-asp-741
source_name: ''
source_type: 4
source_version: ''
start_time: 1762955965257
status: 3
tags: []
user_id: Илья
